# Generated by Django 4.0.6 on 2022-08-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0012_remove_product_country_delete_producingcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('name', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='shop.childcategory', verbose_name='Категория 3-го уровня')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='shop.property', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
                'ordering': ('position',),
            },
        ),
    ]
