# Generated by Django 4.0.6 on 2022-08-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_property_category'),
        ('app_filter', '0002_alter_categoryfilter_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfilter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='shop.subcategory', verbose_name='Категория 2-го уровня'),
        ),
    ]
