# Generated by Django 4.0.6 on 2022-07-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_postworkday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Объект (Постамат, Пункт выдачи)', 'verbose_name_plural': 'Объекты (Постаматы, Пункты выдачи)'},
        ),
        migrations.AddField(
            model_name='post',
            name='object_type',
            field=models.CharField(choices=[('post', 'Постамат'), ('pickup_point', 'Пункт выдачи')], default='post', max_length=255),
        ),
    ]
