# Generated by Django 4.0.6 on 2022-07-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_post_options_post_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='object_type',
            field=models.CharField(choices=[('post', 'Постамат'), ('pickup_point', 'Пункт выдачи')], default='post', max_length=255, verbose_name='Тип объекта'),
        ),
    ]
