# Generated by Django 4.0.6 on 2022-07-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_post_object_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название в ссылке'),
        ),
    ]
