# Generated by Django 4.0.6 on 2022-08-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_alter_city_options_alter_city_name_alter_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postworkday',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
