# Generated by Django 4.0.6 on 2022-08-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_city_position_post_position_postworkday_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='position',
            field=models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='postworkday',
            name='position',
            field=models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='position',
            field=models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция'),
        ),
    ]
