# Generated by Django 4.0.6 on 2022-08-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_alter_useraddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
