# Generated by Django 4.0.6 on 2022-08-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='icon_enum',
            field=models.CharField(choices=[('other', 'Другое'), ('home', 'Дом'), ('office', 'Офис')], default='other', max_length=25),
        ),
    ]
