# Generated by Django 4.0.6 on 2022-09-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_product_categories_product_category'),
        ('location', '0014_useraddress_icon_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='storehouses',
            field=models.ManyToManyField(related_name='storehouses', to='shop.storehouse', verbose_name='Склады'),
        ),
    ]
