# Generated by Django 4.0.6 on 2022-09-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_remove_product_category_product_categories'),
        ('location', '0015_city_storehouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='storehouses',
            field=models.ManyToManyField(related_name='cities', to='shop.storehouse', verbose_name='Склады'),
        ),
    ]
