# Generated by Django 4.0.6 on 2022-09-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_alter_city_storehouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='storehouses',
            field=models.ManyToManyField(related_name='storehouses', to='shop.storehouse', verbose_name='Склады'),
        ),
    ]
