# Generated by Django 4.0.6 on 2022-09-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_alter_city_storehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Расписание'),
        ),
        migrations.DeleteModel(
            name='PostWorkday',
        ),
    ]
