# Generated by Django 4.0.6 on 2022-10-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_alter_useraddress_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commerceml_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место доставки ИД'),
        ),
    ]
