# Generated by Django 4.0.6 on 2022-07-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_stock_created_at_alter_stock_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='story',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userviewedstory',
            name='deleted',
        ),
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный?'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный?'),
        ),
        migrations.AddField(
            model_name='userviewedstory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный?'),
        ),
    ]
