# Generated by Django 4.0.6 on 2022-08-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_remove_stock_deleted_remove_story_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userviewedstory',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
