# Generated by Django 4.0.6 on 2022-08-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_stock_position_alter_story_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Сториз и Баннер', 'verbose_name_plural': 'Сторизы и Баннеры'},
        ),
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.CharField(default='1', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('normal', 'Сториз'), ('mini', 'Мини')], default='normal', max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='story',
            name='deadline',
            field=models.DateTimeField(help_text='После этой даты стори скроется с приложения', verbose_name='Активен до'),
        ),
        migrations.AlterField(
            model_name='story',
            name='deeplink',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для перехода в приложений'),
        ),
        migrations.AlterField(
            model_name='story',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_file',
            field=models.FileField(help_text='фото или видео', upload_to='story/', verbose_name='Файл'),
        ),
    ]
