# Generated by Django 4.0.6 on 2022-08-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_story_options_story_name_story_story_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='deadline',
            field=models.DateTimeField(help_text='После этой даты акция скроется с приложения', verbose_name='Активен до'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='stock/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
