# Generated by Django 4.0.6 on 2022-08-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_stock_options_alter_stock_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('normal', 'Сториз'), ('mini', 'Мини баннер')], default='normal', max_length=50, verbose_name='Тип'),
        ),
    ]
