# Generated by Django 4.0.6 on 2022-08-10 11:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_story_story_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='stock'),
        ),
    ]
