# Generated by Django 4.0.6 on 2022-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_product_in_store_date'),
        ('main_page', '0009_alter_stock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='stocks', to='shop.product'),
        ),
    ]
