# Generated by Django 4.0.6 on 2022-10-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_productimage_options'),
        ('contact', '0006_requisite'),
        ('main_page', '0010_stock_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brand', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory', verbose_name='Категория 2-го уровня'),
        ),
        migrations.AddField(
            model_name='story',
            name='child_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.childcategory', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='story',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.magazine', verbose_name='Tvoy.kz журнал'),
        ),
        migrations.AddField(
            model_name='story',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='story',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.stock', verbose_name='Акция'),
        ),
    ]
