version: '3'

services:
  small_db:
    image: postgres:latest
    container_name: small_db
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - core/.env
    ports:
      - "5432:5432"
    networks:
      main: { }
  redis:
    image: redis
    command: redis-server
    volumes:
      - local_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      main: { }
volumes:
  local_postgres_data: {}
  local_redis_data: {}

networks:
  main: {}