# Generated by Django 4.0.6 on 2022-07-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_badsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='badsms',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
