# Generated by Django 4.0.6 on 2022-07-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_badsms_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badsms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='badsms',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Не активный?'),
        ),
        migrations.AlterField(
            model_name='badsms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
