# Generated by Django 4.0.6 on 2022-07-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_alter_badsms_created_at_alter_badsms_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badsms',
            name='deleted',
        ),
        migrations.AddField(
            model_name='badsms',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный?'),
        ),
    ]
