# Generated by Django 4.0.6 on 2022-07-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_post_object_type'),
        ('auth_user', '0005_remove_badsms_deleted_badsms_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city'),
        ),
    ]
