# Generated by Django 4.0.6 on 2022-07-28 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_question_usefulquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useful_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
