# Generated by Django 4.0.6 on 2022-07-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_alter_usefulquestion_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('ordering',), 'verbose_name': 'Вопросы и ответы', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.AddField(
            model_name='question',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
