# Generated by Django 4.0.6 on 2022-08-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0009_alter_question_options_question_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('position',), 'verbose_name': 'Вопросы и ответы', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ordering',
            new_name='position',
        ),
        migrations.AddField(
            model_name='badsms',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usefulquestion',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
