# Generated by Django 4.0.6 on 2022-08-19 05:58

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0012_favouriteproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('name', models.CharField(max_length=2000)),
                ('icon', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='question_categories')),
            ],
            options={
                'verbose_name': 'Категорию вопросов',
                'verbose_name_plural': 'Категории вопросов',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='auth_user.questioncategory', verbose_name='Категория вопросов'),
        ),
    ]
