# Generated by Django 4.0.6 on 2022-08-19 09:15

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0013_questioncategory_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='question_categories', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='Название'),
        ),
    ]
