# Generated by Django 4.0.6 on 2022-09-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0017_usercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='auth_user.usercard'),
        ),
    ]
