# Generated by Django 4.0.6 on 2022-10-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0018_user_selected_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_common',
            field=models.BooleanField(default=True),
        ),
    ]
