# Generated by Django 4.0.6 on 2022-10-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0021_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
