# Generated by Django 4.0.6 on 2022-07-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ('-permanent', '-activate_to', '-activate_from', '-created_at'), 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
