# Generated by Django 4.0.6 on 2022-08-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_userselectedpromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userselectedpromo',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
