# Generated by Django 4.0.6 on 2022-10-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_alter_promo_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='is_auto',
            field=models.BooleanField(default=True, verbose_name='Автоматический?'),
        ),
    ]
