# Generated by Django 4.0.6 on 2022-10-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0006_promo_is_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='max_order_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promo',
            name='min_order_price',
            field=models.IntegerField(default=0),
        ),
    ]
