# Generated by Django 4.0.6 on 2022-11-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0008_promo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount_type',
            field=models.CharField(choices=[('fix', 'Фиксированное (тг)'), ('percent', 'Процентный (%)')], default='fix', help_text='Тип скидки - % или фиксированное значение', max_length=10, verbose_name='Тип скидки'),
        ),
    ]
