# Generated by Django 4.0.6 on 2022-11-04 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_alter_story_link_type'),
        ('shop', '0052_property_is_multiple'),
        ('notification', '0004_alter_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='banner',
            field=models.ForeignKey(blank=True, limit_choices_to={'story_type': 'mini'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.story', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, limit_choices_to={'main_products__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='notification',
            name='promotion',
            field=models.ForeignKey(blank=True, limit_choices_to={'deadline__gt': django.utils.timezone.now}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.stock', verbose_name='Акция'),
        ),
    ]
