# Generated by Django 4.0.6 on 2022-11-07 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_alter_story_link_type'),
        ('notification', '0006_alter_notification_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='promotion',
            field=models.ForeignKey(blank=True, limit_choices_to={'deadline__gt': datetime.datetime(2022, 11, 7, 6, 5, 55, 178760, tzinfo=utc)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.stock', verbose_name='Акция'),
        ),
    ]
