# Generated by Django 4.0.6 on 2022-11-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_alter_story_link_type'),
        ('notification', '0007_alter_notification_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.stock', verbose_name='Акция'),
        ),
    ]
