# Generated by Django 4.0.6 on 2022-11-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_alter_notification_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='banner',
        ),
    ]
