# Generated by Django 4.0.6 on 2022-08-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link_type', models.CharField(choices=[('tel', 'Номер телефона'), ('link', 'Ссылка на соц. сеть')], default='tel', max_length=5, verbose_name='Тип контакта')),
                ('link', models.CharField(max_length=1000, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ('position',),
            },
        ),
    ]
