# Generated by Django 4.0.6 on 2022-08-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Публичная оферта',
                'verbose_name_plural': 'Публичные оферты',
                'ordering': ('position',),
            },
        ),
    ]
