# Generated by Django 4.0.6 on 2022-08-23 14:51

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_about_aboutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='magazine', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Tvoy.kz Журнал',
                'verbose_name_plural': 'Tvoy.kz Журнал',
                'ordering': ('-is_active', '-created_at'),
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('-is_active', '-created_at'), 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(help_text='в дизайне это `Добро пожаловать в магазин Tvoy.kz`', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about', verbose_name='Картинка'),
        ),
    ]
