# Generated by Django 4.0.6 on 2022-08-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_position_chatmember_position_message_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='position',
            field=models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='position',
            field=models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='message',
            name='position',
            field=models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция'),
        ),
    ]
