# Generated by Django 4.0.6 on 2022-08-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_brand_deleted_remove_category_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
