# Generated by Django 4.0.6 on 2022-08-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_brand_position_alter_category_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Название в ссылке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='shop.subcategory')),
            ],
            options={
                'verbose_name': 'Категорию 3-го уровня',
                'verbose_name_plural': 'Категории 3-го уровня',
            },
        ),
    ]
