# Generated by Django 4.0.6 on 2022-08-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_childcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию 1-го уровня', 'verbose_name_plural': 'Категории 1-го уровня'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Категорию 2-го уровня', 'verbose_name_plural': 'Категории 2-го уровня'},
        ),
    ]
