# Generated by Django 4.0.6 on 2022-08-05 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Название в ссылке')),
                ('version', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Версия')),
                ('barcode', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Штрихкод')),
                ('vendor_code', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Артикул')),
                ('wight', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Вес')),
                ('base_unit', models.CharField(choices=[('796', 'Штук')], default='796', max_length=10, verbose_name='Базовая единица')),
                ('external_id', models.CharField(max_length=1000, verbose_name='ИД в 1с')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.CharField(default=1, max_length=1000, verbose_name='ИД в 1с'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childcategory',
            name='external_id',
            field=models.CharField(default=1, max_length=1000, verbose_name='ИД в 1с'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='external_id',
            field=models.CharField(default=1, max_length=1000, verbose_name='ИД в 1с'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Название в ссылке')),
                ('property_type', models.CharField(choices=[('str', 'Текст'), ('int', 'Целое число'), ('bool', 'Булевы'), ('decimal', 'Десятичная дробь')], default='str', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='shop.childcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Характеристику',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('value', models.CharField(max_length=1000, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='shop.product', verbose_name='Товар')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.property', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристику товара',
                'verbose_name_plural': 'Характеристики товара',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='shop.childcategory', verbose_name='Категории'),
        ),
    ]
