# Generated by Django 4.0.6 on 2022-08-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_category_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='version',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер Версии'),
        ),
        migrations.AddField(
            model_name='childcategory',
            name='version',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер Версии'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brand', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='version',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер Версии'),
        ),
    ]
