# Generated by Django 4.0.6 on 2022-08-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_version_childcategory_version_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wight',
            new_name='weight',
        ),
    ]
