# Generated by Django 4.0.6 on 2022-08-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_producingcountry_product_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.DeleteModel(
            name='ProducingCountry',
        ),
    ]
