# Generated by Django 4.0.6 on 2022-08-10 11:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_country_delete_producingcountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='brand'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='subcategory'),
        ),
    ]
