# Generated by Django 4.0.6 on 2022-08-12 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_alter_city_position_alter_post_position_and_more'),
        ('shop', '0013_alter_brand_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена доставки')),
                ('delivery_type', models.CharField(choices=[('courier', 'Курьер'), ('post', 'Постамат'), ('pickup', 'Самовывоз')], default='courier', max_length=20, verbose_name='Тип доставки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='location.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Доставку',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
