# Generated by Django 4.0.6 on 2022-08-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('courier', 'Курьер'), ('post', 'Постамат'), ('pickup', 'Пункт выдачи заказов')], default='courier', max_length=20, verbose_name='Тип доставки'),
        ),
    ]
