# Generated by Django 4.0.6 on 2022-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_delivery_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, related_name='similar_products', to='shop.product', verbose_name='Другие характеристики'),
        ),
    ]
