# Generated by Django 4.0.6 on 2022-08-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Другие характеристики'),
        ),
    ]
