# Generated by Django 4.0.6 on 2022-08-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_similar_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
    ]
