# Generated by Django 4.0.6 on 2022-08-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_storehouse_productprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Цену', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='storehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='value',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Значение'),
        ),
    ]
