# Generated by Django 4.0.6 on 2022-08-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_productprice_options_alter_storehouse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Значение'),
        ),
    ]
