# Generated by Django 4.0.6 on 2022-08-23 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_productproperty_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_store_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
