# Generated by Django 4.0.6 on 2022-08-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deliveries',
            field=models.ManyToManyField(related_name='products', to='shop.delivery', verbose_name='Способы доставки'),
        ),
    ]
