# Generated by Django 4.0.6 on 2022-09-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_userseenproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='storehouse',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storehouse',
            name='version',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Версия'),
        ),
    ]
