# Generated by Django 4.0.6 on 2022-09-01 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_importstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importstatus',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rests', to='shop.product')),
                ('storehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rests', to='shop.storehouse')),
            ],
        ),
    ]
