# Generated by Django 4.0.6 on 2022-09-06 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='products', to='shop.childcategory',
                                    verbose_name='Категория 3-го уровня'),
            preserve_default=False,
        ),
    ]
