# Generated by Django 4.0.6 on 2022-09-09 05:56

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_remove_product_category_product_categories'),
        ('location', '0017_alter_city_storehouses')
    ]

    operations = [
        migrations.AddField(
            model_name='childcategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='child_category'),
        ),
    ]
