# Generated by Django 4.0.6 on 2022-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('name', models.CharField(max_length=255)),
                ('compilation_type', models.CharField(choices=[('manual', 'Ручная выборка'), ('is_new', 'По новизне'), ('recently', 'Недавно просмотренные')], default='manual', max_length=15)),
                ('products', models.ManyToManyField(related_name='compilations', to='shop.product')),
            ],
            options={
                'verbose_name': 'Выборку',
                'verbose_name_plural': 'Выборки',
            },
        ),
    ]
