# Generated by Django 4.0.6 on 2022-09-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_compilation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='compilation_type',
            field=models.CharField(choices=[('manual', 'Ручная выборка'), ('is_new', 'По новизне'), ('recently', 'Недавно просмотренные')], default='manual', max_length=15, verbose_name='Тип подборки'),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='products',
            field=models.ManyToManyField(related_name='compilations', to='shop.product', verbose_name='Товары'),
        ),
    ]
