# Generated by Django 4.0.6 on 2022-09-30 09:51

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_compilation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
