# Generated by Django 4.0.6 on 2022-10-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_rename_productimages_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Картинку товара', 'verbose_name_plural': 'Картинки товара'},
        ),
    ]
