# Generated by Django 4.0.6 on 2022-10-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_delivery_commerceml_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prices_dict',
            field=models.JSONField(default=dict),
        ),
    ]
