# Generated by Django 4.0.6 on 2022-10-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_product_prices_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rests_dict',
            field=models.JSONField(default=dict),
        ),
    ]
