# Generated by Django 4.0.6 on 2022-11-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_product_rests_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, related_name='main_products', to='shop.product', verbose_name='Другие характеристики'),
        ),
    ]
