# Generated by Django 4.0.6 on 2022-11-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_product_similar_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='same_products',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Похожие'),
        ),
    ]
