# Generated by Django 4.0.6 on 2022-11-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_product_same_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('str', 'Текст'), ('color', 'Цвет'), ('int', 'Целое число'), ('bool', 'Булевы'), ('decimal', 'Десятичная дробь')], default='str', max_length=20),
        ),
    ]
