# Generated by Django 4.0.6 on 2022-11-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_multiple',
            field=models.BooleanField(default=False, verbose_name='Для выборки'),
        ),
    ]
