# Generated by Django 4.0.6 on 2022-11-10 05:33

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_propertyvalue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на главную картинку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='больше не используется', null=True, upload_to='products', verbose_name='Главная картинка'),
        ),
    ]
