# Generated by Django 4.0.6 on 2022-11-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_multiple',
        ),
    ]
