# Generated by Django 4.0.6 on 2022-11-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_remove_property_is_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similar_properties',
            field=models.ManyToManyField(blank=True, related_name='similar_products', to='shop.property', verbose_name='Объединить характеристики'),
        ),
    ]
