# Generated by Django 4.0.6 on 2022-08-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_product_deliveries'),
        ('promo', '0005_alter_promo_position_and_more'),
        ('location', '0014_useraddress_icon_enum'),
        ('order', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарии к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.delivery', verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_accept_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено?'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.payment', verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='promo.promo', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_pay_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='К оплате'),
        ),
        migrations.CreateModel(
            name='OrderDeliverPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='order.order')),
                ('post', models.ForeignKey(limit_choices_to={'is_active': True, 'object_type': 'post'}, on_delete=django.db.models.deletion.CASCADE, related_name='post_orders', to='location.post')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDeliverPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='order.order')),
                ('pickup', models.ForeignKey(limit_choices_to={'is_active': True, 'object_type': 'pickup_point'}, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_orders', to='location.post')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDeliverAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='location.useraddress')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='order.order')),
            ],
        ),
    ]
