# Generated by Django 4.0.6 on 2022-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Цена без скидки'),
        ),
    ]
