# Generated by Django 4.0.6 on 2022-10-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderitem_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
