# Generated by Django 4.0.6 on 2022-10-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket_print_url',
            field=models.URLField(null=True, verbose_name='Ссылка чека(Print)'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_url',
            field=models.URLField(null=True, verbose_name='Ссылка чека'),
        ),
    ]
