# Generated by Django 4.0.6 on 2022-11-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_ticket_print_url_order_ticket_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebkassaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('position', models.IntegerField(default=0, help_text='Для сортировки (по возрастанию)', verbose_name='Позиция')),
                ('token', models.CharField(max_length=10000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
