# Generated by Django 4.0.6 on 2022-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_webkassatoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_slug',
            field=models.CharField(default='almaty', max_length=255),
        ),
    ]
