# Generated by Django 4.0.6 on 2022-11-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_city_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webkassatoken',
            options={'ordering': ('created_at',)},
        ),
    ]
